### PR TITLE
sidebar now has uniform monospace font and all bullets are unfilled c…

### PR DESCRIPTION
**Pull request by westondombroski**
Issue #1 fixed, the class names in the html and css files did not match, thus font and bullet stylings were not applied.

### CODE REVIEW

**Comment by nathanallen** [comment]
Holy wordy commit batman.
Please see https://chris.beams.io/posts/git-commit/

**Comment by nathanallen** [comment]
Just for kicks we're going to have you:
- [amend your commit](http://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commits#179147) to be a little more terse
- [force push](http://stackoverflow.com/questions/41003071/why-must-i-force-push-after-changing-a-commit-message) again to this branch to update your pull request

**Comment by westondombroski** [comment]
sorry, I edited instead of amending... Issue #1 fixed, the class names in the html and css files did not match, thus font and bullet stylings were not applied.

**Comment by nathanallen** [comment]
Okay, but please now also include a brief explanation in your commit message!  (>.<)

**Comment by nathanallen** [comment]
i.e. "fixes #1 - and here's a little message"

**Review by westondombroski — COMMENTED** [review]
The class names in the html and css files did not match, thus font and bullet stylings were not applied.

**Pull request closed without merging**
